# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170320_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set Book As Returned'),)},
        ),
    ]
